### ISSUE TITLE
Plot of VariableSelection - Omits variable names

### ISSUE THREAD

**Issue by dcstang** [barbarabodinier/sharp#1]
I have noticed that when using the `plot` function from `VariableSelection(x)`, some of the variables could be obscured.
This happens if there is particularly a lot of variables (ie. >90) on input data.

As an example below: 
There are variable names that are missing out (demarked by red arrows)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/50109451/185155930-a099bb88-f9ac-41a7-8efd-c153a326b7f4.png)

In case other users comes across this post: Current workaround is to obtain the selection proportions from the function `SelectionProportions(x)` and `Argmax(x)[1,]` to obtain the selection proportions threshold. One can then plot a customised plot with this.

Suggestions:
- autoresizing within plot 
- allowing user to set number of variables to plot (ie. only plot top 20)
- interactive plots

Thanks again for work on this package!

**Comment by barbarabodinier** [comment]
Thanks for the suggestions! All variable names now appear with the latest update of the development version. The font size can be tuned with **cex.axis** and the number of variables to show can be specified in **n_predictors**.
