### ISSUE TITLE
Specifying reference category for multinomial logistic regression

### ISSUE THREAD

**Issue by adawnir** [barbarabodinier/sharp#2]
When using the _VariableSelection()_ function with _family = "multinomial"_, the reference category for the _ydata_ cannot be specified using the original levels of the factor (when _is.factor(ydata) == TRUE_). The _CheckInputRegression()_ function in _check.R_ converts _ydata_ into matrix and applies _as.factor()_ function, resulting in re-ordering of character labels in alphabetical order.

Suggested enhancement: Save original level structure of ydata when _is.factor(ydata) == TRUE_

**Comment by barbarabodinier** [comment]
Thanks for the suggestion, this is now implemented in version 1.3.0.
